const core = require('@actions/core');
const github = require('@actions/github');
const OpenAI = require('openai');

async function run() {
  try {
    const githubToken = core.getInput('github-token', { required: true });
    const openaiApiKey = core.getInput('openai-api-key', { required: true });
    const model = core.getInput('model') || 'gpt-4';
    const summaryPrompt = core.getInput('summary-prompt') || 'You are a code reviewer. Provide a concise summary of the following PR changes in 2-3 sentences.';

    const client = github.getOctokit(githubToken);
    const context = github.context;

    if (!context.payload.pull_request) {
      core.setFailed('This action only runs on pull_request events');
      return;
    }

    const prNumber = context.payload.pull_request.number;
    const prTitle = context.payload.pull_request.title;
    const prBody = context.payload.pull_request.body || '';
    const repoOwner = context.repo.owner;
    const repoRepo = context.repo.repo;

    // Get the diff
    const { data: files } = await client.rest.pulls.listFiles({
      owner: repoOwner,
      repo: repoRepo,
      pull_number: prNumber,
    });

    // Build context from changed files
    let diffContent = '';
    for (const file of files.slice(0, 10)) { // Limit to first 10 files
      diffContent += `## ${file.filename}\n`;
      diffContent += `Status: ${file.status}\n`;
      diffContent += `Changes: +${file.additions} -${file.deletions}\n`;
      if (file.patch) {
        diffContent += `\`\`\`diff\n${file.patch}\n\`\`\`\n`;
      }
    }

    // Call OpenAI API
    const openai = new OpenAI({
      apiKey: openaiApiKey,
    });

    const response = await openai.chat.completions.create({
      model: model,
      messages: [
        {
          role: 'system',
          content: summaryPrompt
        },
        {
          role: 'user',
          content: `PR Title: ${prTitle}\n\nPR Description:\n${prBody}\n\nChanged Files (${files.length} files):\n${diffContent}`
        }
      ],
      temperature: 0.7,
      max_tokens: 500,
    });

    const summary = response.choices[0].message.content;

    // Post comment
    const commentBody = `## 🤖 AI PR Summary\n\n${summary}\n\n---\n*Generated by [PR Summarizer](https://github.com/auto-company/pr-summarizer)*`;

    await client.rest.issues.createComment({
      owner: repoOwner,
      repo: repoRepo,
      issue_number: prNumber,
      body: commentBody,
    });

    core.info('PR summary posted successfully');
  } catch (error) {
    core.setFailed(`Action failed: ${error.message}`);
  }
}

run();
